- name: web app setup
  hosts: windows
  gather_facts: no
  tasks:
    - name: ensure IIS and ASP.NET are installed
      win_feature:
        name: AS-Web-Support

    - name: ensure application dir exists
      win_file:
        path: c:\inetpub\foo
        state: directory

    - name: ensure default.aspx is present
      win_copy:
        src: files/default.aspx
        dest: c:\inetpub\foo\default.aspx

    - name: ensure that the foo web application exists
      win_iis_webapplication:
        name: foo
        physical_path: c:\inetpub\foo
        site: Default Web Site

    - name: announce app
      debug:
        msg: web application is available at http://{{ ansible_ssh_host}}/foo
