- name: stop firewalld
  service:
    name: firewalld
    state: stopped
    
- name: install packages (Red Hat)
  yum: 
    name: "{{ item }}"
    state: present
  with_items: "{{ apache_packages }}"
