---
win_initial_password: myFinalPassword123!

ansible_connection: winrm
ansible_port: 5986
ansible_user: Administrator
ansible_pass: "{{ win_initial_password }}"
ansible_winrm_server_cert_validation: ignore

aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
